title: "My Documentation Site"
description: "A site for PSA, Billing, Architecture docs and more"
theme: jekyll-theme-cayman
url: "https://khallrev.github.io"       
baseurl: "/demo-docs-site" 

navigation:
  - title: "Home"
    url: "/"
  - title: "PSA"
    url: "/psa/"
  - title: "Billing"
    url: "/billing/"
  - title: "Architecture"
    url: "/architecture/"
  - title: "Blog"
    url: "/blog"
